import type { Metadata } from "next";
import "./globals.css";

import { ThemeProvider } from "./components/theme-provider"
import Nav from "./components/Nav";
import CommentSec from "./components/Commentsec";
import Footer from "./components/Footer";
import Pagechange from "./components/Pagechange";


export const metadata: Metadata = {
  title: "Movie Blogs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="scroll-smooth"
        
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
          
          >
<Nav />
            
        {children}
          <Pagechange />
        <CommentSec />
        <Footer />
          </ThemeProvider>
      </body>
    </html>
  );
}
